### ISSUE TITLE
"File to import not found or unreadable: authorization-form."

### ISSUE THREAD

**Issue by zzmarkzz321** [HackMerced/HackMerced-III#36]
Getting this error when running yarn start inside of 2017f. (See image below)
<img width="1280" alt="screen shot 2017-09-06 at 9 34 13 am" src="https://user-images.githubusercontent.com/6733939/30123363-9e9489c2-92e6-11e7-9c7b-c7d207d638a2.png">

**Comment by 4shub** [comment]
Patching error….my bad…gonna write test code for this :P

Shubham Naik

On Wed, Sep 06, 2017 at 9:34 AM Mark Renzo Santiago

<
mailto:Mark Renzo Santiago <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Getting this error when running yarn start inside of 2017f. (See image below)
https://user-images.githubusercontent.com/6733939/30123363-9e9489c2-92e6-11e7-9c7b-c7d207d638a2.png

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/HackMerced/HackMerced/issues/36
, or

**Comment by zzmarkzz321** [comment]
lol sounds good tyty

**Comment by 4shub** [comment]
fixed
